#include <hdos/hdos.hpp>

#include <iostream>
#include <vector>

int main()
{
    /*
     * Five observations and two features, stored column-major:
     *
     *     x1 = [0, 1, 2,  3, 4]
     *     x2 = [1, 0, 2, -1, 3]
     *
     * The response is generated by
     *
     *     y = 1 + 2*x1 - 3*x2.
     */
    const std::vector<double> X{
        0.0, 1.0, 2.0, 3.0, 4.0,
        1.0, 0.0, 2.0, -1.0, 3.0
    };

    const std::vector<double> y{
        -2.0,
        3.0,
        -1.0,
        10.0,
        0.0
    };

    hdos::LinearRegression model(2);
    model.fit(X, y);

    const auto& coefficients =
        model.coefficients();

    std::cout
        << "Intercept: " << model.intercept() << '\n'
        << "Coefficient 1: " << coefficients[0] << '\n'
        << "Coefficient 2: " << coefficients[1] << '\n'
        << "R-squared: " << model.r_squared() << '\n';

    const std::vector<double> observation{
        5.0,
        2.0
    };

    std::cout
        << "Prediction for (5, 2): "
        << model.predict(observation)
        << '\n';
}